### ISSUE TITLE
[FEAT] 이메일 커스터머 회원 가입 기능

### ISSUE THREAD

**Issue by kimdodo97** [8-palbochae/seahere-frontend#11]
## 📝 Description
이메일로 시작하기 선택한 커스터머의 회원 가입 기능 구현

## 📍 Todo
- [x] 회원 가입에 따른 전역 상태관리 기능 구현
- [x] 입력 정보를 서버로 사용자 생성 요청
- [x] 비밀번호 입력 유효성 체크
- [x] 이미 존재하는 이메일 체크
