### ISSUE TITLE
[FEAT] 인증 토큰 발급 로직 구현

### ISSUE THREAD

**Issue by kimdodo97** [8-palbochae/seahere-frontend#23]
## 📝 Description
로그인 후 인증 토큰 발급 로직 구현

## 📍 Todo
- [x] 인증 토큰 전역 관리 기능 구현 (Zustand + Local Storage)
- [x] OAuth2.0 로그인 후 인증 토큰 발급 로직
- [x] 이메일 로그인 후 인증 토큰 발급 로직
