### ISSUE TITLE
[Feature] 매출 통계 첫 화면 기능 구현

### ISSUE THREAD

**Issue by woneveryday** [8-palbochae/seahere-frontend#78]
## 📝 Description
처음 렌더링 될 때, 오늘 통계에 수익, 출고, 입고 얼만지 제일 위에 뜨고
그래프는 입/출고 수익 => 오늘 기준 저번주까지의 통계
어종 통계 => 오늘 기준 통계

## 📍 Todo
- [x] 입/출고 수익 통계 기능
- [x] 어종 통계 기능
- [x] 오늘 통계 기능
